name: "test"

working-dir: /Users/jun/Downloads
env-files:
  - tg.env
jobs:
  os-info:
    steps:
      - name: js
        script: |
          console.log(arg.pr)
      - name: bash
        run: |
          echo ${{ arg.pr }}
      - name: telegram message
        uses: telegram
        with:
          key: ${{ env.TG_BOT_KEY }}
          channel: ${TG_CHANNEL}
          message: "job failed "

