name: "test"

working-dir: /Users/jun/Downloads
env-files:
  - deploy.env
env:
  BACK_BASE_DIR: /Users/jun/Downloads
jobs:
  os-info:
    steps:
      - name: download artifact
        uses: github-actions
        with:
          action: download-artifact
          repository: zhaojunlucky/gundam
          path: ${BACK_BASE_DIR}/artifact
          pr: ${{ arg.pr }}
          artifact-path-env: "GH_GUNDAM_ACITON_ARTIFACT_PATH"
          token: ${GH_TOKEN}
      - run: |
          ls -al ${BACK_BASE_DIR}/artifact
          ls ${GH_GUNDAM_ACITON_ARTIFACT_PATH}