name: "test"

working-dir: /Users/jun/Downloads
env:
  BACK_BASE_DIR: ~/backup

jobs:
  os-info:
    steps:
      - name: get date
        id: date
        script: |
          const curDate = new Date()
          const dateStr = curDate.toISOString().replaceAll(":", "_")
          console.log(JSON.stringify(env.getAll()))
          env.set('BACK_DIR', `${env.get('BACK_BASE_DIR')}/${dateStr}`)
          env.set('DATE_STR', dateStr)
      - run: |
          #printenv
          #ls ~
          PG=$BACK_DIR/PG
          cat bbb.zz || echo "no bbb"
          echo "back dir is $PG"
          echo "=====end======="
#      - name: upload google drive
#        uses: google-drive
#        with:
#          name: site-21-${DATE_STR}.tar.gz.zip
#          path: /Users/jun/Downloads/site-21.tar.gz.zip
#          cred: /Users/jun/Downloads/zhaojunlucky-2db52f66a725.json
#          remote-path: 1HH9HdCPiIhzCbdfYzB5UFmvLZ9xu0OVo
      - name: download artifact
        uses: github-actions
        with:
          action: download-artifact
          repository: zhaojunlucky/gundam
          branch: main
          path: ${BACK_DIR}/artifact
          token: ENC(adcdc)
