name: "test"

working-dir: /Users/jun/Downloads
env:
  BACK_BASE_DIR: ~/backup

jobs:
  os-info:
    steps:
      - name: get date
        id: date
        script: |
          const curDate = new Date()
          const dateStr = curDate.toISOString().replaceAll(":", "_")
          console.log(JSON.stringify(env.getAll()))
          env.set('BACK_DIR', `${env.get('BACK_BASE_DIR')}/${dateStr}`)
          env.set('DATE_STR', dateStr)
      - run: |
          #printenv
          #ls ~
          PG=$BACK_DIR/PG
          cat bbb.zz || echo "no bbb"
          echo "back dir is $PG"
          echo "=====end======="

      - name: js plugin test
        uses: js-plug@latest
        plugin-path: /Users/jun/magicworldz/github/nadleehz/js-plug-example
        with:
          data: this is data

