name: Nadleeh CI

on:
  pull_request:
    branches: [ "main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Set up latest Oracle JDK 21'
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 21
    - name: Cache SonarQube packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Sonarqube
      env:
        HEAD_BRANCH: ${{ github.ref_name }}
        PR_NUM: ${{ github.event.number }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_SERVER }}
      run: |
        curl -o /tmp/sonar.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
        unzip -d /tmp /tmp/sonar.zip
        /tmp/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.pullrequest.github.repository=${{ github.repository }} -Dsonar.projectKey=nadleeh -Dsonar.sources=./src -Dsonar.sourceEncoding=UTF-8  -Dsonar.pullrequest.branch=${HEAD_BRANCH} -Dsonar.pullrequest.base=main -Dsonar.pullrequest.key=${PR_NUM}
