name: Nadleeh CI

on:
  pull_request:
    branches: [ "main"]
    types: [ opened, reopened, synchronize ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'
    - name: Unit Test
      run: go test -cover ./...
    - name: Build
      run: |
        build_date="$(date -u +'%Y-%m-%d')"
        echo "build apple m1"
        env GOOS=darwin GOARCH=arm64 go build -tags=prod -ldflags "-X nadleeh/pkg/common.Version=1.0.${{ github.run_number }} -X nadleeh/pkg/common.BuildDate=${build_date}" -o nadleeh_arm64 -v ./cmd/nadleeh
        echo "build amd64"
        env GOOS=linux GOARCH=amd64 go build -tags=prod -ldflags "-X nadleeh/pkg/common.Version=1.0.${{ github.run_number }} -X nadleeh/pkg/common.BuildDate=${build_date}" -o nadleeh_amd64 -v ./cmd/nadleeh
        tar -czvf nadleeh-PR-${{ github.event.pull_request.number }}-1.0.${{ github.run_number }}.tar.gz nadleeh_amd64 nadleeh_arm64
    - uses: actions/checkout@v4
      with:
        repository: zhaojunlucky/gh-action-script
        path: gh-action-script
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'gh-action-script/yarn.lock'
    - name: artifacts_retention
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PR_NUM: ${{ github.event.pull_request.number }}
      run: |
        cd gh-action-script
        yarn install
        node src/artifact/artifacts_retention.mjs
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nadleeh-PR-${{ github.event.pull_request.number }}-1.0.${{ github.run_number }}.tar.gz
        path: nadleeh-PR-${{ github.event.pull_request.number }}-1.0.${{ github.run_number }}.tar.gz
        
        
